version: 2.1

orbs:
  python: circleci/python@2.1.1
  codecov: codecov/codecov@3.2.4
  semantic-release: trustedshops-public/semantic-release@3.1.5

jobs:
  pip-publish:
    executor: python/default
    parameters:
      repository:
        type: string
        description: Name of the repository to publish to
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Publish package
          command: |
            poetry publish \
              --build \
              --repository <<parameters.repository>> \
              --username "$TWINE_USERNAME" \
              --password "$TWINE_PASSWORD"
  test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: |
            poetry run coverage run -m pytest --junit-xml test-results/junit.xml
            poetry run coverage report
            poetry run coverage html
            poetry run coverage xml -i
      - store_artifacts:
          path: htmlcov
      - store_test_results:
          path: test-results
      - codecov/upload

workflows:
  continuous:
    jobs:
      - test
      - pip-publish:
          name: publish-testpypi
          repository: testpypi
          requires:
            - test
          filters:
            branches:
              only: main
          context:
            - pip-test
      - pip-publish:
          name: publish-pypi
          repository: pypi
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          context:
            - pip-live
      - semantic-release/with-existing-config:
          name: semantic-release
          additional_packages: "@google/semantic-release-replace-plugin"
          requires:
            - test
          context:
            - github-release
          filters:
            branches:
              only:
                # - main
                - disabled-for-now
