version: 2.1

orbs:
  python: circleci/python@2.1.1
  codecov: codecov/codecov@3.2.4

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: |
            poetry run coverage run -m pytest --junit-xml test-results/junit.xml
            poetry run coverage report
            poetry run coverage html
            poetry run coverage xml -i
      - store_artifacts:
          path: htmlcov
      - store_test_results:
          path: test-results
      - codecov/upload

workflows:
  continuous:
    jobs:
      - test
